=== VirtualProgrammingLab/viplab-vue-frontend/viplab-standalone-frontend-vue/src/pages/teacher/json-schema/computation-template-container.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://virtualprogramminglab.github.io/schemas/ComputationTemplateJSONMessage.json",

    "type" : "object",

    "properties" : {
        "identifier" : {
            "type" : "string",
            "description": "uuid; the identifier of this computation template. Can be generated by the frontend launcher"
        },
        "version" : {
            "type" : "string",
            "description": "Version of the json specification; should be given for backwards compatibility"
        },
        "metadata" : {
            "type" : "object",
            "description": "Contains information for frontend",
            "properties" : {
                "displayName" : {
                    "type" : "string",
                    "description" : "Name of computation template shown in frontend"
                },
                "description" : {
                    "type" : "string",
                    "description" : "Short description, mostly a few lines. A longer description should be given outside the computation template."
                },
                "output": {
                    "type": "object",
                    "properties": {
                        "viewer": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "enum" : ["Image", "ParaView", "ViPLabGraphics", "CSV"]
                            },
                            "additionalItems": false
                        },
                        "csv": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "basename" : {
                                        "type" : "string",
                                        "minLength": 1,
                                        "description": "part of filename, that is shared by connected files"
                                    },
                                    "xlabel" : {
                                        "type": "object",
                                        "properties": {
                                            "key" : {
                                                "type" : "string",
                                                "minLength": 1,
                                                "description": "key for x-axis given in csv header"
                                            },
                                            "label" : {
                                                "type" : "string",
                                                "description": "x-axis label for diagram"
                                            },
                                            "factor" : {
                                                "type" : "number",
                                                "description": "Multiply x-values with this factor"
                                            },
                                            "format" : {
                                                "type" : "string",
                                                "description": "Format the x-axis values according to format string - https://github.com/d3/d3-format/blob/main/README.md#locale_format"
                                            }
                                        },
                                        "required": ["key"]
                                    },
                                    "plots" : {
                                        "type" : "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "key" : {
                                                    "type" : "string",
                                                    "minLength": 1,
                                                    "description": "key for y-axis given in csv header"
                                                },
                                                "label" : {
                                                    "type" : "string",
                                                    "description": "y-axis label for diagram"
                                                },
                                                "factor" : {
                                                    "type" : "number",
                                                    "description": "Multiply y-values with this factor"
                                                },
                                                "format" : {
                                                    "type" : "string",
                                                    "description": "Format the y-axis values according to format string - https://github.com/d3/d3-format/blob/main/README.md#locale_format"
                                                }
                                            }
                                        },
                                        "required": ["key"]
                                    }
                                },
                                "required": ["basename"]
                            },
                            "uniqueItems": true,
                            "additionalItems": false
                        },
                        "vtk": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "basename" : {
                                        "type" : "string",
                                        "minLength": 1,
                                        "description": "part of filename, that is shared by connected files"
                                    }
                                },
                                "required": ["basename"]
                            },
                            "uniqueItems": true,
                            "additionalItems": false
                        }
                    }
                }
            },
            "additionalProperties": false
        },
        "environment" : {
            "const": "Container",
            "description" : "Specifies the environment used for the Computation. It defines language, runtime, libraries and tools"
        },
        "files" : {
            "type" : "array",
            "description": "Array containing File objects: there has to be at least one element",
            "items" : {
                "type" : "object",
                "properties": {
                    "identifier" : {
                        "type" : "string",
                        "description": "uuid; for later referencing, has to be unique; can be autogenerated by frontend"
                    },
                    "path" : {
                        "type" : "string",
                        "pattern" : "^([A-z0-9-_+]+/?)*([A-z0-9]+([.]([A-z]+))?)$",
                        "description": "Absolute path to file" 
                    },
                    "metadata" : {
                        "type" : "object",
                        "properties": {
                            "syntaxHighlighting" : {
                                "type" : "string",
                                "enum" : ["abap", "abc", "actionscript", "ada", "alda",
                                          "apache_conf", "apex", "applescript", "aql", "asciidoc",
                                          "asl", "assembly_x86", "autohotkey", "batchfile",
                                          "behaviour", "c9search", "c_cpp", "cirru", "clojure",
                                          "cobol", "coffee", "coldfusion", "crystal", "csharp",
                                          "csound_document", "csound_orchestra",
                                          "csound_preprocessor", "csound_score", "csp", "css",
                                          "curly", "d", "dart", "diff", "django", "doc_comment",
                                          "dockerfile", "dot", "drools", "edifact", "eiffel", "ejs",
                                          "elixir", "elm", "erlang", "forth", "fortran", "fsharp",
                                          "fsl", "ftl", "gcode", "gherkin", "gitignore", "glsl",
                                          "gobstones", "golang", "graphqlschema", "groovy", "haml",
                                          "handlebars", "haskell", "haskell_cabal", "haxe", "hjson",
                                          "html", "html_completions", "html_elixir", "html_ruby",
                                          "ini", "io", "ion", "jack", "jade", "java", "javascript",
                                          "js_regex", "json", "json5", "jsp", "jssm", "jsx",
                                          "julia", "kotlin", "latex", "latte", "less", "liquid",
                                          "lisp", "livescript", "logiql", "logtalk", "lsl", "lua",
                                          "luapage", "lucene", "makefile", "markdown", "mask",
                                          "matching_brace_outdent", "matching_parens_outdent",
                                          "matlab", "maze", "mediawiki", "mel", "mips", "mixal",
                                          "mushcode", "mysql", "nginx", "nim", "nix", "nsis",
                                          "nunjucks", "objectivec", "ocaml", "partiql", "pascal",
                                          "perl", "pgsql", "php", "php_laravel_blade", "pig",
                                          "plain_text", "powershell", "praat", "prisma", "prolog",
                                          "properties", "protobuf", "puppet", "python", "qml", "r",
                                          "raku", "razor", "rdoc", "red", "redshift", "rhtml",
                                          "robot", "rst", "ruby", "rust", "sac", "sass", "scad",
                                          "scala", "scheme", "scrypt", "scss", "sh", "sjs", "slim",
                                          "smarty", "smithy", "snippets", "soy_template", "space",
                                          "sparql", "sql", "sqlserver", "stylus", "svg", "swift",
                                          "tcl", "terraform", "tex", "text", "textile", "toml",
                                          "tsx", "turtle", "twig", "typescript", "vala", "vbscript",
                                          "velocity", "verilog", "vhdl", "visualforce", "wollok",
                                          "xml", "yaml", "zeek"],
                                "description": "Mode of the ace editor. List can be found in on github: https://github.com/ajaxorg/ace/tree/master/src/mode. Examples: 'ini', 'c_cpp', 'matlab', 'java'. See also Ace demo: http://ajaxorg.github.io/ace-builds/kitchen-sink.html"
                            },
                            "MIMEtype" : {
                                "type": "string",
                                "description": "MIMEtype of the content. Examples: text/plain, text/html, text/uri-list, application/x-vgf, application/x-vgf3, application/x-vgfc. Descriptions: text/uri-list: links to websides to be presented in SC; application/x-vgf: generated graphics output in 'ViP graphics format'; application/x-vgf3: generated graphics output in 'ViP graphics format 3D'; application/x-vgfc: generated graphics output in 'ViP graphics format contour plot'"
                            },
                            "description" : {
                                "type": "string",
                                "description": "Additional information about the file, e.g. what it is used for."
                             }

                        },
                        "additionalProperties": false
                    },
                    "parts" : {
                        "type" : "array",
                        "items" : {
                            "type" : "object",
                            "properties": {
                                "identifier" : { 
                                    "type" : "string",
                                    "description": "For later referencing, has to be unique; can be autogenerated by frontend" 
                                },
                                "access" : {
                                    "type" : "string",
                                    "enum" : ["invisible", "visible", "modifiable", "template"],
                                    "description": "Defines the access level of this part for the user. See Notes on access levels for more details: https://virtualprogramminglab.github.io/documentation/viplab3.0/computation_template/#notes-on-access-levels-in-parts"
                                },
                                "metadata" : {
                                    "type" : "object",
                                    "description": "Contains information mainly for the frontend",
                                    "properties": {
                                        "description" : {
                                            "type" : "string",
                                            "description" : "Additional information about this part, e.g., what it is about; can also be a headline."
                                        }
                                    },
                                    "additionalProperties": false
                                },
                                "content" : { 
                                    "type" : "string",
                                    "description": "Base64url encoded source code"
                                }
                            },
                            "if" : {
                                "properties" : { 
                                    "access" : { "const" : "template" } 
                                }
                            },
                            "then" : {
                                "properties" : {
                                    "parameters" : {
                                        "type" : "array",
                                        "description": "Parameters can be used to supply values at runtime to the configuration",
                                        "items" : {
                                            "type": "object"
                                        },
                                        "additionalItems": false,
                                        "minItems" : 1
                                    }
                                }
                            }, 
                            "required" : ["identifier", "access", "content"]
                        },
                        "additionalItems": false,
                        "minItems" : 1
                    }
                },
                "additionalProperties": false,
                "required" : ["identifier", "path", "parts"]
            },
            "additionalItems": false
        },
        "parameters" : {
            "type" : "array",
            "description": "Parameters can be used to supply values at runtime to the configuration",
            "items" : {
                "type": "object"
            },
            "additionalItems": false,
            "minItems" : 1
        },
        "configuration" : {
            "type" : "object",
            "description": "Optional or must (depends on environment). Environment specific configurations; Different phases can be configured like compiling, checking (for legal function calls in source code), ...",
            "properties" : {
                "running.timelimitInSeconds" : { 
                    "type" : "integer",
                    "description": "Optional; CPU time limit. For all environments, for semantics see Notes to 'timelimitInSeconds'"
                },
                "running.commandLineArguments" : { 
                    "type" : "string",
                    "description": "Optional; For C, C++, Java: arguments given to main() function; for DuMuX, Container: additional command line args" 
                },
                "running.entrypoint" : { 
                    "type" : "string",
                    "description": "Must for Container. Executable to run inside the container" 
                },
                "running.userId" : { 
                    "type" : "integer",
                    "description": "user id of the user that writes files inside the container. Needed to set correct permissions" 
                },
                "running.intermediateFilesPattern" : { 
                    "type" : "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "Optional; for Container. Regex-expression in stdout which file is ready to be transferred"
                },
                "resources.image" : { 
                    "type" : "string",
                    "format": "uri",
                    "description": "Must for Container; has to be a tar. Location of the image to be executed" 
                }, 
                "resources.volume" : { 
                    "type" : "string",
                    "description": "Must for Container. Path in the container where data is placed" 
                },
                "resources.memory" : { 
                    "type" : "string",
                    "description": "Optional (64mb); for Container. Memory limit for the container"
                },
                "resources.numCPUs" : { 
                    "type" : "integer",
                    "description": "Optional; for Container. Number of CPUs for the container"
                },
                "resources.diskSpace" : { 
                    "type" : "integer",
                    "description": "Optional; for Container. Disk space limit for the container"
                }
            },
            "additionalProperties": false,
            "required": ["resources.image"]
        }
    },
    "additionalProperties": false,
    "required" : ["identifier", "environment", "configuration"]
}

=== VirtualProgrammingLab/viplab-vue-frontend/viplab-standalone-frontend-vue/src/input/workshop-snakemake-example.computation-template.json
{
    "identifier": "cd39715e-55de-4563-bf8c-929d3d699953",
    "environment": "Container",
    "metadata": {
        "displayName": "Workshop Example",
        "description": "Using Snakemake",
        "output": {
            "viewer": [
                "Image",
                "CSV"
            ],
            "csv": [
                {
                    "basename": "plot_data",
                    "xlabel": {
                        "key": "arc_length",
                        "label": "arc_length"
                    },
                    "plots": [
                        {
                            "key": "function",
                            "label": "function"
                        }
                    ]
                }
            ]
        }
    },
    "files":   [
    { 
        "identifier": "f3fc4404-3529-4962-b252-47bc4ddd02a1",
        "path": "input.yml",
        "metadata": { 
            "syntaxHighlighting": "ini"
        },
        "parts": [
            {
                "identifier": "5fa346f4-85e2-4e16-9cc6-11c82a7d3265",
                "access": "template",
                "metadata": { 
                    "description": "input file"
                },
                "parameters": [
                    {
                        "mode": "any",
                        "identifier": "__scale__",
                        "metadata": {
                            "guiType": "slider",
                            "name": "Scale",
                            "vertical": false,
                            "description" : "Enter value for scale"
                        },
                        "default": [
                            0.05
                        ],
                        "min": 0.05,
                        "max": 10,
                        "step": 0.01,
                        "validation": "range"
                    }
                ],
                "content": "c2NhbGU6IHt7X19zY2FsZV9ffX0NCg"
            }
        ] 
    }
    ],
    "configuration" :
    {   "resources.image": "name://example_snakemake", 
        "resources.volume": "/my_simulation",
        "resources.memory": "1g",
        "resources.numCPUs": 1,
        "running.entrypoint": "snakemake",
        "running.commandLineArguments": "--cores 1"
    }
}

=== VirtualProgrammingLab/viplab-vue-frontend/viplab-standalone-frontend-vue/src/input/parameter-ini.computation-template.json
{
  "identifier": "06fe1cab-0a1a-430a-91c5-badf539189a5",
  "environment": "Container",
  "files":   [
    { 
      "identifier": "22701b37-0a8f-405c-a89b-c31be7cd4b89",
      "path": "parameter_flexi.ini",
      "metadata" :
        { 
          "syntaxHighlighting": "ini"
        },
      "parts": [
        {
          "identifier": "ceb051d8-b50c-4814-983a-b9d703cae0c6",
          "access"    : "modifiable",
          "metadata"  :
              { 
                "description"      : "Main parameters for flexi"
              },
          "content"   : "IT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQohIENvcHlyaWdodCAoYykgMjAxNiAgUHJvZi4gQ2xhdXMtRGlldGVyIE11bnoKISBUaGlzIGZpbGUgaXMgcGFydCBvZiBGTEVYSSwgYSBoaWdoLW9yZGVyIGFjY3VyYXRlIGZyYW1ld29yayBmb3IgbnVtZXJpY2FsbHkgc29sdmluZyBQREVzIHdpdGggZGlzY29udGludW91cyBHYWxlcmtpbiBtZXRob2RzLgohIEZvciBtb3JlIGluZm9ybWF0aW9uIHNlZSBodHRwczovL3d3dy5mbGV4aS1wcm9qZWN0Lm9yZyBhbmQgaHR0cHM6Ly9ucmcuaWFnLnVuaS1zdHV0dGdhcnQuZGUvCiEKISBGTEVYSSBpcyBmcmVlIHNvZnR3YXJlOiB5b3UgY2FuIHJlZGlzdHJpYnV0ZSBpdCBhbmQvb3IgbW9kaWZ5IGl0IHVuZGVyIHRoZSB0ZXJtcyBvZiB0aGUgR05VIEdlbmVyYWwgUHVibGljIExpY2Vuc2UKISBhcyBwdWJsaXNoZWQgYnkgdGhlIEZyZWUgU29mdHdhcmUgRm91bmRhdGlvbiwgZWl0aGVyIHZlcnNpb24gMyBvZiB0aGUgTGljZW5zZSwgb3IgKGF0IHlvdXIgb3B0aW9uKSBhbnkgbGF0ZXIgdmVyc2lvbi4KIQohIEZMRVhJIGlzIGRpc3RyaWJ1dGVkIGluIHRoZSBob3BlIHRoYXQgaXQgd2lsbCBiZSB1c2VmdWwsIGJ1dCBXSVRIT1VUIEFOWSBXQVJSQU5UWTsgd2l0aG91dCBldmVuIHRoZSBpbXBsaWVkIHdhcnJhbnR5CiEgb2YgTUVSQ0hBTlRBQklMSVRZIG9yIEZJVE5FU1MgRk9SIEEgUEFSVElDVUxBUiBQVVJQT1NFLiBTZWUgdGhlIEdOVSBHZW5lcmFsIFB1YmxpYyBMaWNlbnNlIHYzLjAgZm9yIG1vcmUgZGV0YWlscy4KIQohIFlvdSBzaG91bGQgaGF2ZSByZWNlaXZlZCBhIGNvcHkgb2YgdGhlIEdOVSBHZW5lcmFsIFB1YmxpYyBMaWNlbnNlIGFsb25nIHdpdGggRkxFWEkuIElmIG5vdCwgc2VlIDxodHRwOi8vd3d3LmdudS5vcmcvbGljZW5zZXMvPi4KIT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQohCiEgICBUaGlzIGEgcGFyYW1ldGVyIGZpbGUgZm9yIEZsZXhpIChodHRwczovL2ZsZXhpLXByb2plY3Qub3JnKQohCiEgICBVc2FnZTogbXBpcnVuIC1ucCBYWCAuL2ZsZXhpIHRoaXNwYXJhbWV0ZXJmaWxlLmluaSBvcgohICAgICAgICAgIC4vZmxleGkgdGhpc3BhcmFtZXRlcmZpbGUuaW5pCiEKISAgIFN0cnVjdHVyZTogS2V5d29yZCA9IFZhbHVlCiEgICAgICAgICAgICAgIE5vdCBjYXNlIHNlbnNpdGl2ZSwgb3JkZXIgb2Yga2V5d29yZHMgbm90IGltcG9ydGFudAohCiEgICAuL2ZsZXhpIC0taGVscCBmb3IgYSBsaXN0IG9mIGF2YWlsYWJsZSBzZXR0aW5ncwohCiE9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KISA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ICEKISBPVVRQVVQKISA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ICEKUHJvamVjdE5hbWUgICA9IFR1dG9yaWFsX0Nhdml0eV9SZTEwMF9tZXNoMngyCm91dHB1dEZvcm1hdCAgPSAwICAhID0wLCBubyB2aXN1LCA-MCB2aXN1YWxpemUKCiEgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSAhCiEgSU5URVJQT0xBVElPTgohID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0gIQpOICAgICAgICAgICAgID0gMyAhIFBvbHlub21pYWwgZGVncmVlCk5BbmFseXplICAgICAgPSAxMCAhIE51bWJlciBvZiBhbmFseXplIHBvaW50cwoKISA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ICEKISBNRVNICiEgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSAhCk1lc2hGaWxlICAgICAgPSBjYXZpdHkyeDJfbWVzaC5oNQp1c2VDdXJ2ZWRzICAgID0gRgoKIUJvdW5kYXJ5TmFtZT1CQ193YWxsX2xvd2VyCiFCb3VuZGFyeVR5cGU9KC80LDEvKQpCb3VuZGFyeU5hbWU9QkNfd2FsbF9sZWZ0CkJvdW5kYXJ5VHlwZT0oLzQsMS8pCkJvdW5kYXJ5TmFtZT1CQ193YWxsX3JpZ2h0CkJvdW5kYXJ5VHlwZT0oLzQsMS8pCkJvdW5kYXJ5TmFtZT1CQ19mcmVlCkJvdW5kYXJ5VHlwZT0oLzIsMS8pCgohID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0gIQohIEVRVUFUSU9OCiEgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSAhCkluaUV4YWN0RnVuYyAgPSAxCkluaVJlZlN0YXRlICAgPSAyClJlZlN0YXRlICAgICAgPSAoLzEuMCwxLiwwLiwwLiw3MS40Mjg1NzE0Mjg2LykKUmVmU3RhdGUgICAgICA9ICgvMS4wLDAuLDAuLDAuLDcxLjQyODU3MTQyODYvKQptdTAgICAgICAgICAgID0gMC4wMQpSICAgICAgICAgICAgID0gMQpQciAgICAgICAgICAgID0gMC43MgprYXBwYSAgICAgICAgID0gMS40CiEgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSAhCiEgRlYKISA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ICEKRlZfTGltaXRlclR5cGUgPSAxCkluZGljYXRvclR5cGUgID0gMApJbmRWYXIgICAgICAgICA9IDEKISA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ICEKISBUSU1FRElTQwohID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0gIQp0ZW5kICAgICAgICAgID0gNS4wCkFuYWx5emVfZHQgICAgPSAwLjEKbldyaXRlRGF0YSAgICA9IDEKQ0ZMc2NhbGUgICAgICA9IDAuOTkKREZMc2NhbGUgICAgICA9IDAuNAoKISA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ICEKISBBTkFMWVpFCiEgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSAhCkNhbGNFcnJvck5vcm1zPSAgIFQgICAhIENhbGN1bGF0ZSBlcnJvciBub3JtcwpDYWxjQm9keUZvcmNlcz0gICBUICAgISBDYWxjdWxhdGUgYm9keSBmb3JjZXMKQ2FsY1dhbGxWZWxvY2l0eT0gVCAgICEgQ2FsY3VsYXRlIHdhbGwgdmVsb2NpdGllcwpDYWxjTWVhbkZsdXg9ICAgICBUICAgISBDYWxjdWxhdGUgbWVhbiBmbHV4IHRocm91Z2ggYm91bmRhcmllcwoKClZhck5hbWUgPSBQcmVzc3VyZQo"
        }
      ] 
    }
  ],
  "configuration" :
    { "resources.image"  : "file://flexi-docker.tar", 
      "resources.volume" : "/home/jovyan",
      "resources.memory" : "2g",
      "resources.numCPUs" : 2,
      "running.entrypoint" : "/workspace/entrypoint.sh",
      "running.commandLineArguments" : "/home/jovyan/parameter_flexi.ini"
    }
}

=== VirtualProgrammingLab/viplab-vue-frontend/viplab-standalone-frontend-vue/src/input/container.computation-template.json
{
  "identifier": "cd39715e-55de-4563-bf8c-929d3d699953",
  "environment": "Container",
  "files":   [
    { "identifier": "f3fc4404-3529-4962-b252-47bc4ddd02a1",
      "path": "params.input",
      "metadata" :
        { "syntaxHighlighting": "ini"
        },
      "parts": [
        {
          "identifier": "5fa346f4-85e2-4e16-9cc6-11c82a7d3265",
          "access"    : "modifiable",
            "metadata"  :
              { 
                "description" : "params.input file"
              },
            "content"   : ""
          }
        ] 
    }
  ],
  "configuration" :
    { "resources.image"  : "name://git.iws.uni-stuttgart.de:4567/dumux-repositories/dumux-docker/viplab/test", 
      "resources.volume" : "/data/shared",
      "resources.memory" : "1g",
      "resources.numCPUs" : 1,
      "running.entrypoint" : "/data/bin/run.sh",
      "running.commandLineArguments" : "params.input"
    }
}

=== VirtualProgrammingLab/viplab-vue-frontend/viplab-standalone-frontend-vue/src/input/test.json
{
    "identifier": "76eabbbf-b2fa-48da-37eb-f1223c00378f",
    "version": "3.0.0",
    "metadata": {
        "displayName": "",
        "description": "",
        "output": {
            "viewer": [],
            "csv": [],
            "vtk": []
        }
    },
    "environment": "Container",
    "configuration": {
    "resources.image": "name://t",
    "resources.memory": "4g",
    "resources.numCPUs": 1
    },
    "files": [],
    "parameters": [
        {
            "mode": "any",
            "identifier": "658c0db4-91e5-3118-ae09-82f468362a0f",
            "metadata": {
              "guiType": "input_field",
              "type": "text",
              "name": "Name",
              "description": "Add your description here..."
            },
            "default": [
              "dGVzdA"
            ],
            "validation": "none"
          }
    ]
}
