=== VirtualProgrammingLab/viplab-vue-frontend/viplab-standalone-frontend-vue/src/pages/teacher/json-schema/computation-template-container.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://virtualprogramminglab.github.io/schemas/ComputationTemplateJSONMessage.json",

    "type" : "object",

    "properties" : {
        "identifier" : {
            "type" : "string",
            "description": "uuid; the identifier of this computation template. Can be generated by the frontend launcher"
        },
        "version" : {
            "type" : "string",
            "description": "Version of the json specification; should be given for backwards compatibility"
        },
        "metadata" : {
            "type" : "object",
            "description": "Contains information for frontend",
            "properties" : {
                "displayName" : {
                    "type" : "string",
                    "description" : "Name of computation template shown in frontend"
                },
                "description" : {
                    "type" : "string",
                    "description" : "Short description, mostly a few lines. A longer description should be given outside the computation template."
                },
                "output": {
                    "type": "object",
                    "properties": {
                        "viewer": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "enum" : ["Image", "ParaView", "ViPLabGraphics", "CSV"]
                            },
                            "additionalItems": false
                        },
                        "csv": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "basename" : {
                                        "type" : "string",
                                        "minLength": 1,
                                        "description": "part of filename, that is shared by connected files"
                                    },
                                    "xlabel" : {
                                        "type": "object",
                                        "properties": {
                                            "key" : {
                                                "type" : "string",
                                                "minLength": 1,
                                                "description": "key for x-axis given in csv header"
                                            },
                                            "label" : {
                                                "type" : "string",
                                                "description": "x-axis label for diagram"
                                            },
                                            "factor" : {
                                                "type" : "number",
                                                "description": "Multiply x-values with this factor"
                                            },
                                            "format" : {
                                                "type" : "string",
                                                "description": "Format the x-axis values according to format string - https://github.com/d3/d3-format/blob/main/README.md#locale_format"
                                            }
                                        },
                                        "required": ["key"]
                                    },
                                    "plots" : {
                                        "type" : "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "key" : {
                                                    "type" : "string",
                                                    "minLength": 1,
                                                    "description": "key for y-axis given in csv header"
                                                },
                                                "label" : {
                                                    "type" : "string",
                                                    "description": "y-axis label for diagram"
                                                },
                                                "factor" : {
                                                    "type" : "number",
                                                    "description": "Multiply y-values with this factor"
                                                },
                                                "format" : {
                                                    "type" : "string",
                                                    "description": "Format the y-axis values according to format string - https://github.com/d3/d3-format/blob/main/README.md#locale_format"
                                                }
                                            }
                                        },
                                        "required": ["key"]
                                    }
                                },
                                "required": ["basename"]
                            },
                            "uniqueItems": true,
                            "additionalItems": false
                        },
                        "vtk": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "basename" : {
                                        "type" : "string",
                                        "minLength": 1,
                                        "description": "part of filename, that is shared by connected files"
                                    }
                                },
                                "required": ["basename"]
                            },
                            "uniqueItems": true,
                            "additionalItems": false
                        }
                    }
                }
            },
            "additionalProperties": false
        },
        "environment" : {
            "const": "Container",
            "description" : "Specifies the environment used for the Computation. It defines language, runtime, libraries and tools"
        },
        "files" : {
            "type" : "array",
            "description": "Array containing File objects: there has to be at least one element",
            "items" : {
                "type" : "object",
                "properties": {
                    "identifier" : {
                        "type" : "string",
                        "description": "uuid; for later referencing, has to be unique; can be autogenerated by frontend"
                    },
                    "path" : {
                        "type" : "string",
                        "pattern" : "^([A-z0-9-_+]+/?)*([A-z0-9]+([.]([A-z]+))?)$",
                        "description": "Absolute path to file" 
                    },
                    "metadata" : {
                        "type" : "object",
                        "properties": {
                            "syntaxHighlighting" : {
                                "type" : "string",
                                "enum" : ["abap", "abc", "actionscript", "ada", "alda",
                                          "apache_conf", "apex", "applescript", "aql", "asciidoc",
                                          "asl", "assembly_x86", "autohotkey", "batchfile",
                                          "behaviour", "c9search", "c_cpp", "cirru", "clojure",
                                          "cobol", "coffee", "coldfusion", "crystal", "csharp",
                                          "csound_document", "csound_orchestra",
                                          "csound_preprocessor", "csound_score", "csp", "css",
                                          "curly", "d", "dart", "diff", "django", "doc_comment",
                                          "dockerfile", "dot", "drools", "edifact", "eiffel", "ejs",
                                          "elixir", "elm", "erlang", "forth", "fortran", "fsharp",
                                          "fsl", "ftl", "gcode", "gherkin", "gitignore", "glsl",
                                          "gobstones", "golang", "graphqlschema", "groovy", "haml",
                                          "handlebars", "haskell", "haskell_cabal", "haxe", "hjson",
                                          "html", "html_completions", "html_elixir", "html_ruby",
                                          "ini", "io", "ion", "jack", "jade", "java", "javascript",
                                          "js_regex", "json", "json5", "jsp", "jssm", "jsx",
                                          "julia", "kotlin", "latex", "latte", "less", "liquid",
                                          "lisp", "livescript", "logiql", "logtalk", "lsl", "lua",
                                          "luapage", "lucene", "makefile", "markdown", "mask",
                                          "matching_brace_outdent", "matching_parens_outdent",
                                          "matlab", "maze", "mediawiki", "mel", "mips", "mixal",
                                          "mushcode", "mysql", "nginx", "nim", "nix", "nsis",
                                          "nunjucks", "objectivec", "ocaml", "partiql", "pascal",
                                          "perl", "pgsql", "php", "php_laravel_blade", "pig",
                                          "plain_text", "powershell", "praat", "prisma", "prolog",
                                          "properties", "protobuf", "puppet", "python", "qml", "r",
                                          "raku", "razor", "rdoc", "red", "redshift", "rhtml",
                                          "robot", "rst", "ruby", "rust", "sac", "sass", "scad",
                                          "scala", "scheme", "scrypt", "scss", "sh", "sjs", "slim",
                                          "smarty", "smithy", "snippets", "soy_template", "space",
                                          "sparql", "sql", "sqlserver", "stylus", "svg", "swift",
                                          "tcl", "terraform", "tex", "text", "textile", "toml",
                                          "tsx", "turtle", "twig", "typescript", "vala", "vbscript",
                                          "velocity", "verilog", "vhdl", "visualforce", "wollok",
                                          "xml", "yaml", "zeek"],
                                "description": "Mode of the ace editor. List can be found in on github: https://github.com/ajaxorg/ace/tree/master/src/mode. Examples: 'ini', 'c_cpp', 'matlab', 'java'. See also Ace demo: http://ajaxorg.github.io/ace-builds/kitchen-sink.html"
                            },
                            "MIMEtype" : {
                                "type": "string",
                                "description": "MIMEtype of the content. Examples: text/plain, text/html, text/uri-list, application/x-vgf, application/x-vgf3, application/x-vgfc. Descriptions: text/uri-list: links to websides to be presented in SC; application/x-vgf: generated graphics output in 'ViP graphics format'; application/x-vgf3: generated graphics output in 'ViP graphics format 3D'; application/x-vgfc: generated graphics output in 'ViP graphics format contour plot'"
                            },
                            "description" : {
                                "type": "string",
                                "description": "Additional information about the file, e.g. what it is used for."
                             }

                        },
                        "additionalProperties": false
                    },
                    "parts" : {
                        "type" : "array",
                        "items" : {
                            "type" : "object",
                            "properties": {
                                "identifier" : { 
                                    "type" : "string",
                                    "description": "For later referencing, has to be unique; can be autogenerated by frontend" 
                                },
                                "access" : {
                                    "type" : "string",
                                    "enum" : ["invisible", "visible", "modifiable", "template"],
                                    "description": "Defines the access level of this part for the user. See Notes on access levels for more details: https://virtualprogramminglab.github.io/documentation/viplab3.0/computation_template/#notes-on-access-levels-in-parts"
                                },
                                "metadata" : {
                                    "type" : "object",
                                    "description": "Contains information mainly for the frontend",
                                    "properties": {
                                        "description" : {
                                            "type" : "string",
                                            "description" : "Additional information about this part, e.g., what it is about; can also be a headline."
                                        }
                                    },
                                    "additionalProperties": false
                                },
                                "content" : { 
                                    "type" : "string",
                                    "description": "Base64url encoded source code"
                                }
                            },
                            "if" : {
                                "properties" : { 
                                    "access" : { "const" : "template" } 
                                }
                            },
                            "then" : {
                                "properties" : {
                                    "parameters" : {
                                        "type" : "array",
                                        "description": "Parameters can be used to supply values at runtime to the configuration",
                                        "items" : {
                                            "type": "object"
                                        },
                                        "additionalItems": false,
                                        "minItems" : 1
                                    }
                                }
                            }, 
                            "required" : ["identifier", "access", "content"]
                        },
                        "additionalItems": false,
                        "minItems" : 1
                    }
                },
                "additionalProperties": false,
                "required" : ["identifier", "path", "parts"]
            },
            "additionalItems": false
        },
        "parameters" : {
            "type" : "array",
            "description": "Parameters can be used to supply values at runtime to the configuration",
            "items" : {
                "type": "object"
            },
            "additionalItems": false,
            "minItems" : 1
        },
        "configuration" : {
            "type" : "object",
            "description": "Optional or must (depends on environment). Environment specific configurations; Different phases can be configured like compiling, checking (for legal function calls in source code), ...",
            "properties" : {
                "running.timelimitInSeconds" : { 
                    "type" : "integer",
                    "description": "Optional; CPU time limit. For all environments, for semantics see Notes to 'timelimitInSeconds'"
                },
                "running.commandLineArguments" : { 
                    "type" : "string",
                    "description": "Optional; For C, C++, Java: arguments given to main() function; for DuMuX, Container: additional command line args" 
                },
                "running.entrypoint" : { 
                    "type" : "string",
                    "description": "Must for Container. Executable to run inside the container" 
                },
                "running.userId" : { 
                    "type" : "integer",
                    "description": "user id of the user that writes files inside the container. Needed to set correct permissions" 
                },
                "running.intermediateFilesPattern" : { 
                    "type" : "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "Optional; for Container. Regex-expression in stdout which file is ready to be transferred"
                },
                "resources.image" : { 
                    "type" : "string",
                    "format": "uri",
                    "description": "Must for Container; has to be a tar. Location of the image to be executed" 
                }, 
                "resources.volume" : { 
                    "type" : "string",
                    "description": "Must for Container. Path in the container where data is placed" 
                },
                "resources.memory" : { 
                    "type" : "string",
                    "description": "Optional (64mb); for Container. Memory limit for the container"
                },
                "resources.numCPUs" : { 
                    "type" : "integer",
                    "description": "Optional; for Container. Number of CPUs for the container"
                },
                "resources.diskSpace" : { 
                    "type" : "integer",
                    "description": "Optional; for Container. Disk space limit for the container"
                }
            },
            "additionalProperties": false,
            "required": ["resources.image"]
        }
    },
    "additionalProperties": false,
    "required" : ["identifier", "environment", "configuration"]
}

=== VirtualProgrammingLab/viplab-vue-frontend/viplab-standalone-frontend-vue/src/input/workshop-bash-example.computation-template.json
{
    "identifier": "cd39715e-55de-4563-bf8c-929d3d699953",
    "environment": "Container",
    "metadata": {
    "displayName": "Workshop Example",
    "description": "Using Bash",
    "output": {
        "viewer": [
            "Image",
            "CSV"
        ]
    }
    },
    "files":   [],
    "parameters": [
        {
            "mode": "fixed",
            "identifier": "__scale__",
            "metadata": {
                "guiType": "dropdown",
                "name": "Scale",
                "description" : "Select value for scale"
            },
            "options": [
                {
                    "value": "0.05",
                    "selected": true
                },
                {
                    "value": "0.5"
                },
                {
                    "value": "1"
                }
            ],
            "validation": "oneof"
        }
    ],
    "configuration" :
    { "resources.image": "name://example_snakemake", 
        "resources.volume": "/my_simulation",
        "resources.memory": "1g",
        "resources.numCPUs": 1,
        "running.entrypoint": "./automation.sh",
        "running.commandLineArguments": "{{__scale__}}"
    }
}

=== VirtualProgrammingLab/viplab-vue-frontend/viplab-standalone-frontend-vue/src/input/viplab-computation-template.json
{
  "identifier": "cd39715e-55de-4563-bf8c-929d3d699953",
  "environment": "Container",
  "metadata": {
    "displayName": "DuMux Benchmark Case 1",
    "description": "Case 1: Single Fracture",
    "output": {
        "viewer": [
        ],
        "vtk": [
            {
                "basename": "1ptestfv"
            } 
        ]
    }
  },
  "files":   [
    { "identifier": "f3fc4404-3529-4962-b252-47bc4ddd02a1",
      "path": "params.input",
      "metadata" :
        { 
          "syntaxHighlighting": "ini"
        },
      "parts": [
        {
          "identifier": "5fa346f4-85e2-4e16-9cc6-11c82a7d3265",
          "access"    : "modifiable",
            "metadata"  :
              { 
                "description"      : "params.input file"
              },
            "content"   : 
"W1RpbWVMb29wXQpEdEluaXRpYWwgPSAxICMgW3NdClRFbmQgPSAxICMgW3NdCgpbR3JpZF0KTG93ZXJMZWZ0ID0gMCAwClVwcGVyUmlnaHQgPSAxIDEKQ2VsbHMgPSAxMCAxMAoKW1Byb2JsZW1dCk5hbWUgPSAxcHRlc3RmdiAjIG5hbWUgcGFzc2VkIHRvIHRoZSBvdXRwdXQgcm91dGluZXMKCltTcGF0aWFsUGFyYW1zXQpMZW5zTG93ZXJMZWZ0ID0gMC4yIDAuMgpMZW5zVXBwZXJSaWdodCA9IDAuOCAwLjgKClBlcm1lYWJpbGl0eSA9IDFlLTEwICMgW21eMl0KUGVybWVhYmlsaXR5TGVucyA9IDFlLTEyICMgW21eMl0K"
          }
        ] 
    }
  ],
  "configuration" :
    { "resources.image"  : 
"name://git.iws.uni-stuttgart.de:4567/dumux-repositories/dumux-docker/viplab/test", 
      "resources.volume" : "/data/shared",
      "resources.memory" : "1g",
      "resources.numCPUs" : 1,
      "running.entrypoint" : "/data/bin/run.sh",
      "running.commandLineArguments" : "params.input"
    }
}

=== VirtualProgrammingLab/viplab-vue-frontend/viplab-standalone-frontend-vue/src/input/case1.computation-template.json
{
  "identifier": "11483f23-95bf-424a-98a5-ee5868c85c3f",
  "version": "3.0.0",
  "metadata": {
    "displayName": "Fracture Benchmark (Case 1): Single Fracture",
    "description": "In this application, flow and transport through a single fracture in a cubic domain can be simulated with the numerical schemes available in Dumux, which comprise two cell-centered (tpfa, mpfa) and a vertex-centered finite volume scheme (box). Further details can be found in the related publication doi.org/10.1016/j.advwatres.2020.103759 .",
    "output": {
      "viewer": [
        "CSV",
        "ParaView"
      ],
      "ignore": ["results.csv"],
      "csv": [
        {
          "basename": "dataovertime",
          "xlabel": {
            "key": "time",
            "label": "Time in years",
            "factor": 3.1709792E-8,
            "format": ".2f"
          },
          "plots": [
            {
              "key": "massBottomLayer",
              "label": "Tracer mass in bottom layer in kg",
              "factor": 100
            },
            {
              "key": "massFracture",
              "label": "Tracer mass in fracture in kg"
            },
            {
              "key": "fluxAcrossOutlet",
              "label": "Flux across outlet in mg/(s m^2)",
              "factor": 1E6,
              "format": ".2f"
            }
          ]
        }
      ],
      "vtk": [
        {
          "basename": "case1_single_tracer_matrix"
        },
        {
          "basename": "case1_single_tracer_fracture"
        },
        {
          "basename": "case1_single_onep_matrix"
        },
        {
          "basename": "case1_single_onep_fracture"
        }
      ]
    }
  },
  "environment": "Container",
  "files": [
    {
      "identifier": "22483f42-95bf-984a-98a5-ee9485c85c3f",
      "path": "params.input",
      "metadata": {
        "syntaxHighlighting": "ini",
        "description": "params.input is the main configuration file for DuMux"
      },
      "parts": [
        {
          "identifier": "f3fc4404-3529-4962-b252-47bc4ddd02a2",
          "access": "template",
          "metadata": {
            "description": "Use the form fields to adjust a subset of parameters defined in 'params.input' of DuMux"
          },
          "parameters": [
            {
              "mode": "fixed",
              "identifier": "Discretization",
              "metadata": {
                "guiType": "dropdown",
                "name": "Discretization Method",
                "description": "Choose the discretization method. You can choose between three different finite volume (FV) methods implemented in DuMux."
              },
              "options": [
                {
                  "value": "tpfa",
                  "text": "TPFA (Cell Centered FV Scheme with Two-Point Flux Approximation)",
                  "selected": true
                },
                {
                  "value": "mpfa",
                  "text": "MPFA-O (Cell-Centered FV Scheme with Multi-Point Flux Approximation)"
                },
                {
                  "value": "box",
                  "text": "BOX (Vertex-Centered FV Scheme)"
                }
              ],
              "validation": "oneof"
            },
            {
              "mode": "fixed",
              "identifier": "Transport",
              "metadata": {
                "guiType": "radio",
                "name": "Solved Model Equations",
                "description": "Choose if the simulation stops after computing a stationary flow field, or if a subsequent transport simulation is carried out."
              },
              "options": [
                {
                  "value": "false",
                  "text": "Only Flow"
                },
                {
                  "value": "true",
                  "text": "Flow and Transport",
                  "selected": true
                }
              ],
              "validation": "oneof"
            },
            {
              "mode": "fixed",
              "identifier": "MeshFile",
              "metadata": {
                "guiType": "dropdown",
                "name": "Computational Grid",
                "description": "Select the total number of cells in the computational grid: coarse means ~1k cells, intermediate ~10k cells and fine ~100k cells."
              },
              "options": [
                {
                  "value": "single_1k.msh",
                  "text": "Coarse (1k Cells)",
                  "selected": true
                },
                {
                  "value": "single_10k.msh",
                  "text": "Intermediate (10k Cells)"
                },
                {
                  "value": "single_100k.msh",
                  "text": "Fine (100k Cells)"
                }
              ],
              "validation": "oneof"
            }
          ],
          "content": "W1RpbWVMb29wXQ0KVEVuZCA9IDFlOQ0KRHQgPSAxZTcNCg0KW1Byb2JsZW1dDQpFbmFibGVHcmF2aXR5ID0gZmFsc2UNClNvbHZlVHJhbnNwb3J0ID0ge3sgVHJhbnNwb3J0IH19DQoNCltEaXNjcmV0aXphdGlvbl0NClNjaGVtZSA9IHt7IERpc2NyZXRpemF0aW9uIH19DQoNCltHcmlkXQ0KRmlsZSA9IC9kYXRhL2JlcnJlMjAyMC9idWlsZC1jbWFrZS9jYXNlcy90cmFuc3BvcnQvY2FzZTFfc2luZ2xlZnJhY3R1cmUvZ3JpZHMve3sgTWVzaEZpbGUgfX0NCg0KW01hdHJpeF0NCk9uZVAuUHJvYmxlbS5OYW1lID0gb25lcF9tYXRyaXgNClRyYWNlci5Qcm9ibGVtLk5hbWUgPSB0cmFjZXJfbWF0cml4DQoNCltGcmFjdHVyZV0NCk9uZVAuUHJvYmxlbS5OYW1lID0gb25lcF9mcmFjdHVyZQ0KVHJhY2VyLlByb2JsZW0uTmFtZSA9IHRyYWNlcl9mcmFjdHVyZQ0KDQpbQ29tcG9uZW50XQ0KTGlxdWlkRGVuc2l0eSA9IDEuMA0KTGlxdWlkS2luZW1hdGljVmlzY29zaXR5ID0gMS4wDQoNCltWdGtdDQpPdXRwdXROYW1lID0gY2FzZTFfc2luZ2xlDQoNCltJT10NCkNsZWFyUmVzdWx0RmlsZSA9IHRydWUNClJlZmluZW1lbnQgPSAwDQoNCltBc3NlbWJseV0NCk51bWVyaWNEaWZmZXJlbmNlLkJhc2VFcHNpbG9uID0gMWUxMA0KDQpbTmV3dG9uXQ0KRW5hYmxlRHluYW1pY091dHB1dCA9IGZhbHNl"
        }
      ]
    }
  ],
  "configuration": {
    "resources.image": "name://berre2020",
    "resources.volume": "/data/shared",
    "resources.memory": "4g",
    "resources.numCPUs": 1,
    "running.commandLineArguments": "case1 params.input",
    "running.entrypoint": "/data/berre2020/docker/run.sh",
    "running.intermediateFilesPattern": ["XFtcW1dyb3RlIFthLXpcc10rXF1cXSAoW1x3Li1dKyk="]
  }
}
